### ISSUE TITLE
Label is hidden when value is `false`

### ISSUE THREAD

**Issue by yeya** [danielgindi/dom-selectbox#3]
When `items=[true, false]` and `false` is selected - the label of the selected item is hidden

![selectbox-false](https://user-images.githubusercontent.com/6382246/223671865-b6cbd9bf-6707-4c68-96f2-47cd8ce61362.gif)

**Comment by danielgindi** [comment]
That's not a bug but a feature :) 
Whenever the label is `false`, it is hidden in the tag box ui.
It is meant to be used when specifying `shortLabel` for the tag ui, so it could show in the list but not in the box.
