### ISSUE TITLE
Link to a simple test page

### ISSUE THREAD

**Issue by yeya** [danielgindi/dom-selectbox#5]
[stackblitz](https://stackblitz.com/edit/vitejs-vite-xxxul9)

**Comment by danielgindi** [comment]
1.  `value-prop="id"`
2. Down arrow IS flipped

**Comment by yeya** [comment]
1. I changed to value instead id, doesn't help. 
2. Only in `auto` or `ltr`, but after changing to `rtl` - does not flipped.
3. Default `rtl` doesn't work, need to change direction after load.

**Comment by danielgindi** [comment]
1. You didn't
2-3. Initial value issue has been fixed

**Comment by yeya** [comment]
I update the package in Stackblitz.

- The open indicator doesn't flip on `direction: 'rtl'`
- On `multi` mode - Placeholder location ignores the direction prop, and follow only the div direction.

**Comment by danielgindi** [comment]
> 1. I changed to value instead id, doesn't help. 
You've only changed in listItems2
 
> 2. Only in `auto` or `ltr`, but after changing to `rtl` - does not flipped.
It does for me 😀 
 
> 3. Default `rtl` doesn't work, need to change direction after load.

You mean with the latest version?

**Comment by yeya** [comment]
> I update the package in Stackblitz.
> 
> * The open indicator doesn't flip on `direction: 'rtl'`
> * On `multi` mode - Placeholder location ignores the direction prop, and follow only the div direction.

At the latest version (2.0.8) I found only this 2 issues, not the old ones.
